(cl:in-package roboy_middleware_msgs-msg)
(cl:export '(GLOBAL_ID-VAL
          GLOBAL_ID
          SETPOINT-VAL
          SETPOINT
          CONTROL_MODE-VAL
          CONTROL_MODE
          KP-VAL
          KP
          KI-VAL
          KI
          KD-VAL
          KD
          DEADBAND-VAL
          DEADBAND
          INTEGRALLIMIT-VAL
          INTEGRALLIMIT
          PWMLIMIT-VAL
          PWMLIMIT
          PWM-VAL
          PWM
          CURRENT_LIMIT-VAL
          CURRENT_LIMIT
          COMMUNICATION_QUALITY-VAL
          COMMUNICATION_QUALITY
          ERROR_CODE-VAL
          ERROR_CODE
          NEOPIXELCOLOR-VAL
          NEOPIXELCOLOR
))