// Generated by gencpp from file roboy_simulation_msgs/BodyInformation.msg
// DO NOT EDIT!


#ifndef ROBOY_SIMULATION_MSGS_MESSAGE_BODYINFORMATION_H
#define ROBOY_SIMULATION_MSGS_MESSAGE_BODYINFORMATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <roboy_simulation_msgs/LinkInformation.h>

namespace roboy_simulation_msgs
{
template <class ContainerAllocator>
struct BodyInformation_
{
  typedef BodyInformation_<ContainerAllocator> Type;

  BodyInformation_()
    : link_information()  {
    }
  BodyInformation_(const ContainerAllocator& _alloc)
    : link_information(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::roboy_simulation_msgs::LinkInformation_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::roboy_simulation_msgs::LinkInformation_<ContainerAllocator> >> _link_information_type;
  _link_information_type link_information;





  typedef boost::shared_ptr< ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator> const> ConstPtr;

}; // struct BodyInformation_

typedef ::roboy_simulation_msgs::BodyInformation_<std::allocator<void> > BodyInformation;

typedef boost::shared_ptr< ::roboy_simulation_msgs::BodyInformation > BodyInformationPtr;
typedef boost::shared_ptr< ::roboy_simulation_msgs::BodyInformation const> BodyInformationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator1> & lhs, const ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator2> & rhs)
{
  return lhs.link_information == rhs.link_information;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator1> & lhs, const ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roboy_simulation_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9273ff30caabd7d7a45c37f2cda988ff";
  }

  static const char* value(const ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9273ff30caabd7d7ULL;
  static const uint64_t static_value2 = 0xa45c37f2cda988ffULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_simulation_msgs/BodyInformation";
  }

  static const char* value(const ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# list containing all links and some information like name, dimensions etc.\n"
"roboy_simulation_msgs/LinkInformation[] link_information\n"
"================================================================================\n"
"MSG: roboy_simulation_msgs/LinkInformation\n"
"# id of the link in the simulation\n"
"int32 id\n"
"# name of the link in the simulation\n"
"string name\n"
"# dimentions of the link\n"
"geometry_msgs/Vector3 dimensions\n"
"# initial pose of the link\n"
"geometry_msgs/Pose init_pose\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.link_information);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BodyInformation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_simulation_msgs::BodyInformation_<ContainerAllocator>& v)
  {
    s << indent << "link_information[]" << std::endl;
    for (size_t i = 0; i < v.link_information.size(); ++i)
    {
      s << indent << "  link_information[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::roboy_simulation_msgs::LinkInformation_<ContainerAllocator> >::stream(s, indent + "    ", v.link_information[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_SIMULATION_MSGS_MESSAGE_BODYINFORMATION_H
