// Generated by gencpp from file roboy_simulation_msgs/UpdateBodyInformation.msg
// DO NOT EDIT!


#ifndef ROBOY_SIMULATION_MSGS_MESSAGE_UPDATEBODYINFORMATION_H
#define ROBOY_SIMULATION_MSGS_MESSAGE_UPDATEBODYINFORMATION_H

#include <ros/service_traits.h>


#include <roboy_simulation_msgs/UpdateBodyInformationRequest.h>
#include <roboy_simulation_msgs/UpdateBodyInformationResponse.h>


namespace roboy_simulation_msgs
{

struct UpdateBodyInformation
{

typedef UpdateBodyInformationRequest Request;
typedef UpdateBodyInformationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateBodyInformation
} // namespace roboy_simulation_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboy_simulation_msgs::UpdateBodyInformation > {
  static const char* value()
  {
    return "e428186c93531a8d1164969320286db9";
  }

  static const char* value(const ::roboy_simulation_msgs::UpdateBodyInformation&) { return value(); }
};

template<>
struct DataType< ::roboy_simulation_msgs::UpdateBodyInformation > {
  static const char* value()
  {
    return "roboy_simulation_msgs/UpdateBodyInformation";
  }

  static const char* value(const ::roboy_simulation_msgs::UpdateBodyInformation&) { return value(); }
};


// service_traits::MD5Sum< ::roboy_simulation_msgs::UpdateBodyInformationRequest> should match
// service_traits::MD5Sum< ::roboy_simulation_msgs::UpdateBodyInformation >
template<>
struct MD5Sum< ::roboy_simulation_msgs::UpdateBodyInformationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_simulation_msgs::UpdateBodyInformation >::value();
  }
  static const char* value(const ::roboy_simulation_msgs::UpdateBodyInformationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_simulation_msgs::UpdateBodyInformationRequest> should match
// service_traits::DataType< ::roboy_simulation_msgs::UpdateBodyInformation >
template<>
struct DataType< ::roboy_simulation_msgs::UpdateBodyInformationRequest>
{
  static const char* value()
  {
    return DataType< ::roboy_simulation_msgs::UpdateBodyInformation >::value();
  }
  static const char* value(const ::roboy_simulation_msgs::UpdateBodyInformationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboy_simulation_msgs::UpdateBodyInformationResponse> should match
// service_traits::MD5Sum< ::roboy_simulation_msgs::UpdateBodyInformation >
template<>
struct MD5Sum< ::roboy_simulation_msgs::UpdateBodyInformationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_simulation_msgs::UpdateBodyInformation >::value();
  }
  static const char* value(const ::roboy_simulation_msgs::UpdateBodyInformationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_simulation_msgs::UpdateBodyInformationResponse> should match
// service_traits::DataType< ::roboy_simulation_msgs::UpdateBodyInformation >
template<>
struct DataType< ::roboy_simulation_msgs::UpdateBodyInformationResponse>
{
  static const char* value()
  {
    return DataType< ::roboy_simulation_msgs::UpdateBodyInformation >::value();
  }
  static const char* value(const ::roboy_simulation_msgs::UpdateBodyInformationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOY_SIMULATION_MSGS_MESSAGE_UPDATEBODYINFORMATION_H
