// Generated by gencpp from file roboy_simulation_msgs/UpdateBodyInformationResponse.msg
// DO NOT EDIT!


#ifndef ROBOY_SIMULATION_MSGS_MESSAGE_UPDATEBODYINFORMATIONRESPONSE_H
#define ROBOY_SIMULATION_MSGS_MESSAGE_UPDATEBODYINFORMATIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_simulation_msgs
{
template <class ContainerAllocator>
struct UpdateBodyInformationResponse_
{
  typedef UpdateBodyInformationResponse_<ContainerAllocator> Type;

  UpdateBodyInformationResponse_()
    : ret_code(0)
    , msg()  {
    }
  UpdateBodyInformationResponse_(const ContainerAllocator& _alloc)
    : ret_code(0)
    , msg(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _ret_code_type;
  _ret_code_type ret_code;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _msg_type;
  _msg_type msg;





  typedef boost::shared_ptr< ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateBodyInformationResponse_

typedef ::roboy_simulation_msgs::UpdateBodyInformationResponse_<std::allocator<void> > UpdateBodyInformationResponse;

typedef boost::shared_ptr< ::roboy_simulation_msgs::UpdateBodyInformationResponse > UpdateBodyInformationResponsePtr;
typedef boost::shared_ptr< ::roboy_simulation_msgs::UpdateBodyInformationResponse const> UpdateBodyInformationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator1> & lhs, const ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ret_code == rhs.ret_code &&
    lhs.msg == rhs.msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator1> & lhs, const ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roboy_simulation_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1560a47c93faf133f52fff45f7590ff7";
  }

  static const char* value(const ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1560a47c93faf133ULL;
  static const uint64_t static_value2 = 0xf52fff45f7590ff7ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_simulation_msgs/UpdateBodyInformationResponse";
  }

  static const char* value(const ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 ret_code\n"
"string msg\n"
;
  }

  static const char* value(const ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ret_code);
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateBodyInformationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_simulation_msgs::UpdateBodyInformationResponse_<ContainerAllocator>& v)
  {
    s << indent << "ret_code: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ret_code);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_SIMULATION_MSGS_MESSAGE_UPDATEBODYINFORMATIONRESPONSE_H
