(cl:in-package bench_pkg-srv)
(cl:export '(CURRENT_ANGLE-VAL
          CURRENT_ANGLE
          CURRENT_ANGULAR_VELOCITY-VAL
          CURRENT_ANGULAR_VELOCITY
          CURRENT_ANGULAR_ACCELERATION-VAL
          CURRENT_ANGULAR_ACCELERATION
          DESIRED_ANGLE-VAL
          DESIRED_ANGLE
          DESIRED_ANGULAR_VELOCITY-VAL
          DESIRED_ANGULAR_VELOCITY
          DESIRED_ANGULAR_ACCELERATION-VAL
          DESIRED_ANGULAR_ACCELERATION
          FLEX_MYOBRICK_PWM-VAL
          FLEX_MYOBRICK_PWM
          EXTEND_MYOBRICK_PWM-VAL
          EXTEND_MYOBRICK_PWM
))