(cl:in-package bench_pkg-srv)
(cl:export '(FLEX_MYOBRICK_PWM-VAL
          FLEX_MYOBRICK_PWM
          EXTEND_MYOBRICK_PWM-VAL
          EXTEND_MYOBRICK_PWM
          DURATION-VAL
          DURATION
          CURRENT_ANGLE-VAL
          CURRENT_ANGLE
          CURRENT_ANGULAR_VELOCITY-VAL
          CURRENT_ANGULAR_VELOCITY
          CURRENT_ANGULAR_ACCELERATION-VAL
          CURRENT_ANGULAR_ACCELERATION
))