// Generated by gencpp from file roboy_control_msgs/SpatialUpdate.msg
// DO NOT EDIT!


#ifndef ROBOY_CONTROL_MSGS_MESSAGE_SPATIALUPDATE_H
#define ROBOY_CONTROL_MSGS_MESSAGE_SPATIALUPDATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_control_msgs
{
template <class ContainerAllocator>
struct SpatialUpdate_
{
  typedef SpatialUpdate_<ContainerAllocator> Type;

  SpatialUpdate_()
    : header()
    , data()  {
    }
  SpatialUpdate_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _header_type;
  _header_type header;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator> const> ConstPtr;

}; // struct SpatialUpdate_

typedef ::roboy_control_msgs::SpatialUpdate_<std::allocator<void> > SpatialUpdate;

typedef boost::shared_ptr< ::roboy_control_msgs::SpatialUpdate > SpatialUpdatePtr;
typedef boost::shared_ptr< ::roboy_control_msgs::SpatialUpdate const> SpatialUpdateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator1> & lhs, const ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator1> & lhs, const ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roboy_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1c847f0c793a4a3afd39df9fc36b8b5a";
  }

  static const char* value(const ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1c847f0c793a4a3aULL;
  static const uint64_t static_value2 = 0xfd39df9fc36b8b5aULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_control_msgs/SpatialUpdate";
  }

  static const char* value(const ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] header\n"
"uint8[] data\n"
;
  }

  static const char* value(const ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpatialUpdate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_control_msgs::SpatialUpdate_<ContainerAllocator>& v)
  {
    s << indent << "header[]" << std::endl;
    for (size_t i = 0; i < v.header.size(); ++i)
    {
      s << indent << "  header[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.header[i]);
    }
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_CONTROL_MSGS_MESSAGE_SPATIALUPDATE_H
