// Generated by gencpp from file roboy_middleware_msgs/MotorState.msg
// DO NOT EDIT!


#ifndef ROBOY_MIDDLEWARE_MSGS_MESSAGE_MOTORSTATE_H
#define ROBOY_MIDDLEWARE_MSGS_MESSAGE_MOTORSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace roboy_middleware_msgs
{
template <class ContainerAllocator>
struct MotorState_
{
  typedef MotorState_<ContainerAllocator> Type;

  MotorState_()
    : header()
    , global_id()
    , setpoint()
    , encoder0_pos()
    , encoder1_pos()
    , displacement()
    , current()  {
    }
  MotorState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , global_id(_alloc)
    , setpoint(_alloc)
    , encoder0_pos(_alloc)
    , encoder1_pos(_alloc)
    , displacement(_alloc)
    , current(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _global_id_type;
  _global_id_type global_id;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _setpoint_type;
  _setpoint_type setpoint;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _encoder0_pos_type;
  _encoder0_pos_type encoder0_pos;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _encoder1_pos_type;
  _encoder1_pos_type encoder1_pos;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _displacement_type;
  _displacement_type displacement;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _current_type;
  _current_type current;





  typedef boost::shared_ptr< ::roboy_middleware_msgs::MotorState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_middleware_msgs::MotorState_<ContainerAllocator> const> ConstPtr;

}; // struct MotorState_

typedef ::roboy_middleware_msgs::MotorState_<std::allocator<void> > MotorState;

typedef boost::shared_ptr< ::roboy_middleware_msgs::MotorState > MotorStatePtr;
typedef boost::shared_ptr< ::roboy_middleware_msgs::MotorState const> MotorStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_middleware_msgs::MotorState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_middleware_msgs::MotorState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roboy_middleware_msgs::MotorState_<ContainerAllocator1> & lhs, const ::roboy_middleware_msgs::MotorState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.global_id == rhs.global_id &&
    lhs.setpoint == rhs.setpoint &&
    lhs.encoder0_pos == rhs.encoder0_pos &&
    lhs.encoder1_pos == rhs.encoder1_pos &&
    lhs.displacement == rhs.displacement &&
    lhs.current == rhs.current;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roboy_middleware_msgs::MotorState_<ContainerAllocator1> & lhs, const ::roboy_middleware_msgs::MotorState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roboy_middleware_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::MotorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::MotorState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::MotorState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::MotorState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::MotorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::MotorState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_middleware_msgs::MotorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "61eb6482f6cdc52e983eb5e8d69b0aaf";
  }

  static const char* value(const ::roboy_middleware_msgs::MotorState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x61eb6482f6cdc52eULL;
  static const uint64_t static_value2 = 0x983eb5e8d69b0aafULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_middleware_msgs::MotorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_middleware_msgs/MotorState";
  }

  static const char* value(const ::roboy_middleware_msgs::MotorState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_middleware_msgs::MotorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8[] global_id\n"
"float32[] setpoint\n"
"float32[] encoder0_pos\n"
"float32[] encoder1_pos\n"
"float32[] displacement\n"
"float32[] current\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::roboy_middleware_msgs::MotorState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_middleware_msgs::MotorState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.global_id);
      stream.next(m.setpoint);
      stream.next(m.encoder0_pos);
      stream.next(m.encoder1_pos);
      stream.next(m.displacement);
      stream.next(m.current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_middleware_msgs::MotorState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_middleware_msgs::MotorState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "global_id[]" << std::endl;
    for (size_t i = 0; i < v.global_id.size(); ++i)
    {
      s << indent << "  global_id[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.global_id[i]);
    }
    s << indent << "setpoint[]" << std::endl;
    for (size_t i = 0; i < v.setpoint.size(); ++i)
    {
      s << indent << "  setpoint[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.setpoint[i]);
    }
    s << indent << "encoder0_pos[]" << std::endl;
    for (size_t i = 0; i < v.encoder0_pos.size(); ++i)
    {
      s << indent << "  encoder0_pos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.encoder0_pos[i]);
    }
    s << indent << "encoder1_pos[]" << std::endl;
    for (size_t i = 0; i < v.encoder1_pos.size(); ++i)
    {
      s << indent << "  encoder1_pos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.encoder1_pos[i]);
    }
    s << indent << "displacement[]" << std::endl;
    for (size_t i = 0; i < v.displacement.size(); ++i)
    {
      s << indent << "  displacement[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.displacement[i]);
    }
    s << indent << "current[]" << std::endl;
    for (size_t i = 0; i < v.current.size(); ++i)
    {
      s << indent << "  current[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.current[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_MIDDLEWARE_MSGS_MESSAGE_MOTORSTATE_H
