// Generated by gencpp from file roboy_middleware_msgs/Neopixel.msg
// DO NOT EDIT!


#ifndef ROBOY_MIDDLEWARE_MSGS_MESSAGE_NEOPIXEL_H
#define ROBOY_MIDDLEWARE_MSGS_MESSAGE_NEOPIXEL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_middleware_msgs
{
template <class ContainerAllocator>
struct Neopixel_
{
  typedef Neopixel_<ContainerAllocator> Type;

  Neopixel_()
    : motor()
    , r(0)
    , g(0)
    , b(0)  {
    }
  Neopixel_(const ContainerAllocator& _alloc)
    : motor(_alloc)
    , r(0)
    , g(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _motor_type;
  _motor_type motor;

   typedef uint8_t _r_type;
  _r_type r;

   typedef uint8_t _g_type;
  _g_type g;

   typedef uint8_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::roboy_middleware_msgs::Neopixel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_middleware_msgs::Neopixel_<ContainerAllocator> const> ConstPtr;

}; // struct Neopixel_

typedef ::roboy_middleware_msgs::Neopixel_<std::allocator<void> > Neopixel;

typedef boost::shared_ptr< ::roboy_middleware_msgs::Neopixel > NeopixelPtr;
typedef boost::shared_ptr< ::roboy_middleware_msgs::Neopixel const> NeopixelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_middleware_msgs::Neopixel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_middleware_msgs::Neopixel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roboy_middleware_msgs::Neopixel_<ContainerAllocator1> & lhs, const ::roboy_middleware_msgs::Neopixel_<ContainerAllocator2> & rhs)
{
  return lhs.motor == rhs.motor &&
    lhs.r == rhs.r &&
    lhs.g == rhs.g &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roboy_middleware_msgs::Neopixel_<ContainerAllocator1> & lhs, const ::roboy_middleware_msgs::Neopixel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roboy_middleware_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::Neopixel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::Neopixel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::Neopixel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::Neopixel_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::Neopixel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::Neopixel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_middleware_msgs::Neopixel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f0e4f657f53f3d67f7671e397b0b14d";
  }

  static const char* value(const ::roboy_middleware_msgs::Neopixel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f0e4f657f53f3d6ULL;
  static const uint64_t static_value2 = 0x7f7671e397b0b14dULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_middleware_msgs::Neopixel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_middleware_msgs/Neopixel";
  }

  static const char* value(const ::roboy_middleware_msgs::Neopixel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_middleware_msgs::Neopixel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] motor\n"
"uint8 r\n"
"uint8 g\n"
"uint8 b\n"
;
  }

  static const char* value(const ::roboy_middleware_msgs::Neopixel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_middleware_msgs::Neopixel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor);
      stream.next(m.r);
      stream.next(m.g);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Neopixel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_middleware_msgs::Neopixel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_middleware_msgs::Neopixel_<ContainerAllocator>& v)
  {
    s << indent << "motor[]" << std::endl;
    for (size_t i = 0; i < v.motor.size(); ++i)
    {
      s << indent << "  motor[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.motor[i]);
    }
    s << indent << "r: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.r);
    s << indent << "g: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.g);
    s << indent << "b: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_MIDDLEWARE_MSGS_MESSAGE_NEOPIXEL_H
