// Generated by gencpp from file roboy_middleware_msgs/SystemStatus.msg
// DO NOT EDIT!


#ifndef ROBOY_MIDDLEWARE_MSGS_MESSAGE_SYSTEMSTATUS_H
#define ROBOY_MIDDLEWARE_MSGS_MESSAGE_SYSTEMSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <roboy_middleware_msgs/BodyPart.h>

namespace roboy_middleware_msgs
{
template <class ContainerAllocator>
struct SystemStatus_
{
  typedef SystemStatus_<ContainerAllocator> Type;

  SystemStatus_()
    : header()
    , body_parts()  {
    }
  SystemStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , body_parts(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::roboy_middleware_msgs::BodyPart_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::roboy_middleware_msgs::BodyPart_<ContainerAllocator> >> _body_parts_type;
  _body_parts_type body_parts;





  typedef boost::shared_ptr< ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator> const> ConstPtr;

}; // struct SystemStatus_

typedef ::roboy_middleware_msgs::SystemStatus_<std::allocator<void> > SystemStatus;

typedef boost::shared_ptr< ::roboy_middleware_msgs::SystemStatus > SystemStatusPtr;
typedef boost::shared_ptr< ::roboy_middleware_msgs::SystemStatus const> SystemStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator1> & lhs, const ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.body_parts == rhs.body_parts;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator1> & lhs, const ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roboy_middleware_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a154f05d39fafbb9bb8a98f0b5bb4351";
  }

  static const char* value(const ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa154f05d39fafbb9ULL;
  static const uint64_t static_value2 = 0xbb8a98f0b5bb4351ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_middleware_msgs/SystemStatus";
  }

  static const char* value(const ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"BodyPart[] body_parts\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: roboy_middleware_msgs/BodyPart\n"
"# Sample values\n"
"uint8 ENABLED=0\n"
"uint8 DISABLED=1\n"
"uint8 ERROR_CONDITION_A=2\n"
"uint8 ERROR_CONDITION_B=3\n"
"\n"
"# Body part designator\n"
"string name\n"
"\n"
"# Status byte implemented like Unix return codes:\n"
"# 0: All OK / Ready\n"
"# 1: Function disabled\n"
"# 2-100: Custom error codes indicating different stop conditions or\n"
"# malfunctions.\n"
"# 100-255: Custom readiness states. Some functionality still online / waiting\n"
"# for something.\n"
"#\n"
"uint8 status\n"
;
  }

  static const char* value(const ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.body_parts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SystemStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_middleware_msgs::SystemStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "body_parts[]" << std::endl;
    for (size_t i = 0; i < v.body_parts.size(); ++i)
    {
      s << indent << "  body_parts[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::roboy_middleware_msgs::BodyPart_<ContainerAllocator> >::stream(s, indent + "    ", v.body_parts[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_MIDDLEWARE_MSGS_MESSAGE_SYSTEMSTATUS_H
