# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roboy_simulation_msgs/ContactPoint.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class ContactPoint(genpy.Message):
  _md5sum = "32832356e1139e4e5fd083337d208b0e"
  _type = "roboy_simulation_msgs/ContactPoint"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#id of roboy link in which a collision happened
int64 linkid
#position of contact point on roboy in link frame
geometry_msgs/Vector3 position
#contact normal on external body, pointing towards roboy
geometry_msgs/Vector3 contactnormal
#contact distance, positive for separation, negative for penetration
float64 contactdistance
#normal force applied during the last 'stepSimulation'
float64 normalforce
================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['linkid','position','contactnormal','contactdistance','normalforce']
  _slot_types = ['int64','geometry_msgs/Vector3','geometry_msgs/Vector3','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       linkid,position,contactnormal,contactdistance,normalforce

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ContactPoint, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.linkid is None:
        self.linkid = 0
      if self.position is None:
        self.position = geometry_msgs.msg.Vector3()
      if self.contactnormal is None:
        self.contactnormal = geometry_msgs.msg.Vector3()
      if self.contactdistance is None:
        self.contactdistance = 0.
      if self.normalforce is None:
        self.normalforce = 0.
    else:
      self.linkid = 0
      self.position = geometry_msgs.msg.Vector3()
      self.contactnormal = geometry_msgs.msg.Vector3()
      self.contactdistance = 0.
      self.normalforce = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_q8d().pack(_x.linkid, _x.position.x, _x.position.y, _x.position.z, _x.contactnormal.x, _x.contactnormal.y, _x.contactnormal.z, _x.contactdistance, _x.normalforce))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Vector3()
      if self.contactnormal is None:
        self.contactnormal = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.linkid, _x.position.x, _x.position.y, _x.position.z, _x.contactnormal.x, _x.contactnormal.y, _x.contactnormal.z, _x.contactdistance, _x.normalforce,) = _get_struct_q8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_q8d().pack(_x.linkid, _x.position.x, _x.position.y, _x.position.z, _x.contactnormal.x, _x.contactnormal.y, _x.contactnormal.z, _x.contactdistance, _x.normalforce))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Vector3()
      if self.contactnormal is None:
        self.contactnormal = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.linkid, _x.position.x, _x.position.y, _x.position.z, _x.contactnormal.x, _x.contactnormal.y, _x.contactnormal.z, _x.contactdistance, _x.normalforce,) = _get_struct_q8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_q8d = None
def _get_struct_q8d():
    global _struct_q8d
    if _struct_q8d is None:
        _struct_q8d = struct.Struct("<q8d")
    return _struct_q8d
