# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roboy_simulation_msgs/LinkInformation.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class LinkInformation(genpy.Message):
  _md5sum = "da41a99dfc52d4f683b6fe3c478f8696"
  _type = "roboy_simulation_msgs/LinkInformation"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# id of the link in the simulation
int32 id
# name of the link in the simulation
string name
# dimentions of the link
geometry_msgs/Vector3 dimensions
# initial pose of the link
geometry_msgs/Pose init_pose
================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['id','name','dimensions','init_pose']
  _slot_types = ['int32','string','geometry_msgs/Vector3','geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,name,dimensions,init_pose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LinkInformation, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.name is None:
        self.name = ''
      if self.dimensions is None:
        self.dimensions = geometry_msgs.msg.Vector3()
      if self.init_pose is None:
        self.init_pose = geometry_msgs.msg.Pose()
    else:
      self.id = 0
      self.name = ''
      self.dimensions = geometry_msgs.msg.Vector3()
      self.init_pose = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.id
      buff.write(_get_struct_i().pack(_x))
      _x = self.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_10d().pack(_x.dimensions.x, _x.dimensions.y, _x.dimensions.z, _x.init_pose.position.x, _x.init_pose.position.y, _x.init_pose.position.z, _x.init_pose.orientation.x, _x.init_pose.orientation.y, _x.init_pose.orientation.z, _x.init_pose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.dimensions is None:
        self.dimensions = geometry_msgs.msg.Vector3()
      if self.init_pose is None:
        self.init_pose = geometry_msgs.msg.Pose()
      end = 0
      start = end
      end += 4
      (self.id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.dimensions.x, _x.dimensions.y, _x.dimensions.z, _x.init_pose.position.x, _x.init_pose.position.y, _x.init_pose.position.z, _x.init_pose.orientation.x, _x.init_pose.orientation.y, _x.init_pose.orientation.z, _x.init_pose.orientation.w,) = _get_struct_10d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.id
      buff.write(_get_struct_i().pack(_x))
      _x = self.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_10d().pack(_x.dimensions.x, _x.dimensions.y, _x.dimensions.z, _x.init_pose.position.x, _x.init_pose.position.y, _x.init_pose.position.z, _x.init_pose.orientation.x, _x.init_pose.orientation.y, _x.init_pose.orientation.z, _x.init_pose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.dimensions is None:
        self.dimensions = geometry_msgs.msg.Vector3()
      if self.init_pose is None:
        self.init_pose = geometry_msgs.msg.Pose()
      end = 0
      start = end
      end += 4
      (self.id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.dimensions.x, _x.dimensions.y, _x.dimensions.z, _x.init_pose.position.x, _x.init_pose.position.y, _x.init_pose.position.z, _x.init_pose.orientation.x, _x.init_pose.orientation.y, _x.init_pose.orientation.z, _x.init_pose.orientation.w,) = _get_struct_10d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10d = None
def _get_struct_10d():
    global _struct_10d
    if _struct_10d is None:
        _struct_10d = struct.Struct("<10d")
    return _struct_10d
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
